######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 14 10:23:09 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mouse.h \
    score.h
FORMS += mouse.ui \
    score.ui
SOURCES += main.cpp mouse.cpp \
    score.cpp
RESOURCES += mouse.qrc
